[tool.poetry]
name = "numato-gpio"
version = "0.13.0"
description = "Python API for Numato GPIO Expanders"
authors = ["Henning Claßen <code@clssn.de>"]
license = "MIT License"
readme = "README.md"

classifiers=[
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Homepage = "https://github.com/clssn/numato-gpio"
Repository = "https://github.com/clssn/numato-gpio.git"

[tool.poetry.scripts]
numato = "numato_gpio.cli.cmd_numato:app"
numato-discover = "numato_gpio.cli.cmd_discover:app"

[tool.poetry.dependencies]
python = "^3.8.1"
pyserial = "^3.1"
click = "^8.1.7"
rich = "^13.7.1"
typer = "^0.12.3"
anyio = "^4.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
flake8 = "^6.1.0"
bandit = "^1.7.5"
pytest-xdist = "^3.5.0"
pytest-cov = "^4.1.0"
pylint = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

