name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clean-code:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Format
        run: uvx ruff format --check

      - name: Lint
        run: uvx ruff check --no-fix

      - name: Pre-commit
        run: uvx pre-commit run --all

  tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}  # yamllint disable-line rule:line-length
      cancel-in-progress: true

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Test
        run: uv run --python=${{ matrix.python-version }} pytest tests/
