name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Test
        run: make test

      - name: Check Format
        run: uvx ruff format --check

      - name: Lint
        run: uvx ruff check --select=ALL --no-fix
